FROM node:20.10.0

WORKDIR /usr/src/app

RUN npm install -g @nestjs/cli

# Copy application dependency manifests to the container image.
# Copying this first prevents re-running npm install on every code change.
COPY package*.json ./

COPY . .

CMD rm -rf node_modules && rm -rf yarn.lock && yarn install && \
  yarn start:dev
